name: Deploy to cPanel
on:
  push:
    branches:
      - main

env:
  APP_NAME: "Rezaul Karim"
  APP_URL: "https://reza.nexxenit.com"
  REMOTE_USER: "ezbitlyc"
  REMOTE_HOST: "reza.nexxenit.com"
  REMOTE_PATH: "/home/ezbitlyc/reza.nexxenit.com"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Removed: Send Start Notification

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm install

      - name: Build project
        id: build
        run: |
          START_TIME=$(date +%s)
          npm run build
          END_TIME=$(date +%s)
          BUILD_TIME=$((END_TIME - START_TIME))
          echo "::set-output name=build_time::$BUILD_TIME"

      - name: Install SSH Keys
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
          if_key_exists: replace

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${REMOTE_HOST} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        id: deploy
        run: |
          cp .htaccess dist/
          START_TIME=$(date +%s)
          FOLDER_SIZE=$(du -sh dist | cut -f1)

          if rsync -avz --delete ./dist/ ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH}/; then
            END_TIME=$(date +%s)
            UPLOAD_TIME=$((END_TIME - START_TIME))
            echo "Files uploaded successfully."
          else
            echo "Upload failed during rsync operation"
            exit 1
          fi

      # Removed: Notify on Failure